version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      production-dependencies:
        applies-to: 'version-updates'
        dependency-type: 'production'
        patterns:
          - '*'
      development-dependencies:
        applies-to: 'version-updates'
        dependency-type: 'development'
        patterns:
          - '*'
    ignore:
      - dependency-name: 'typescript'
        update-types:
          - 'version-update:semver-major'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      ci-dependencies:
        applies-to: 'version-updates'
        patterns:
          - '*'
